# Generated by Django 6.0.6 on 2026-07-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_connection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
    ]
